spring:
  profiles: heroku
eureka:
  client:
    serviceUrl:
      defaultZone: https://ffkr-discovery-service.herokuapp.com/eureka/
zuul:
  prefix: /api
  routes:
    tournament-service:
      path: /**
      serviceId: tournament-service
---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
zuul:
  prefix: /api
  routes:
    tournament-service:
      path: /**
      serviceId: tournament-service
server:
  port: 8102