eureka:
  instance:
    instanceId: ${spring.application.name}:${ffkr-api.instanceId}:${server.port}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,configprops
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    configprops:
      enabled: true
zuul:
  prefix: /api
  routes:
    ffkr-article:
      path: /articles/**
      serviceId: ffkr-article
      strip-prefix: false
    ffkr-auth:
      path: /auth/**
      serviceId: ffkr-auth
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie
server:
  port: 8102

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
logging:
  file: "/ffkr-api/logs/ffkr_api.log"
