spring:
  main:
    banner-mode: "log"
  rabbitmq:
      host: ${rabbitmq.host}
      port: ${rabbitmq.port}
      username: ${rabbitmq.username}
      password: ${rabbitmq.password}
  data:
    mongodb:
      host: ${mongodb.host}
      port: ${mongodb.port}
      database: ${mongodb.database}
      username: ${mongodb.username}
      password: ${mongodb.password}
eureka:
  instance:
    instanceId: ${spring.application.name}:${ffkr-article.instanceId}:${server.port}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,configprops
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    configprops:
      enabled: true
logging:
  config: classpath:logback.xml
ffkr:
  article:
    crawler:
      start-page: http://football.ua/newsarc/page%d.html
    image-location: /usr/local/share/ffkr/photos
server:
  port: 8105

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
---

spring:
  profiles: docker
  hymeleaf:
    checkTemplateLocation: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
logging:
  file: "/ffkr-article/logs/ffkr-article.log"
