eureka:
  instance:
    instanceId: ${spring.application.name}:${ffkr-api.instanceId}:${server.port}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,configprops
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    configprops:
      enabled: true
zuul:
  prefix: /api
  routes:
    ffkr-tournament:
      path: /tournament-service/**
      serviceId: ffkr-tournament
    ffkr-article:
      path: /article-service/**
      serviceId: ffkr-article
server:
  port: 8102

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
