spring:
  profiles: heroku
eureka:
  client:
    serviceUrl:
      defaultZone: https://ffkr-discovery.herokuapp.com/eureka/
  instance:
    hostname: ffkr-auth.herokuapp.com

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8106
management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
server:
  port: 8106
