spring:
  data:
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
security:
  basic:
    enabled: false
eureka:
  instance:
    instanceId: ${spring.application.name}:${ffkr-tournament.instanceId}:${server.port}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,configprops
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    configprops:
      enabled: true
server:
  port: 8103

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ffkr
    username: os
    password: os

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://tournament-db:5432/ffkr
    username: os
    password: os
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
