spring:
  data:
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
  datasource:
    url: jdbc:${db.vendor}://{db.host}:${db.port}/${db.database}
    username: ${db.user}
    password: ${db.password}
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
server:
  port: 8103

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8100/eureka/
