eureka:
  instance:
    instanceId: ${spring.application.name}:${ffkr-auth.instanceId}:${server.port}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,configprops
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    configprops:
      enabled: true
server:
  port: 8107
---
spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
---
spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
logging:
  file: "/ffkr-auth/logs/ffkr_auth.log"
