spring:
  profiles: heroku
eureka:
  client:
    serviceUrl:
      defaultZone: https://ffkr-discovery.herokuapp.com/eureka/
  instance:
    hostname: ffkr-api.herokuapp.com
management:
  security:
    enabled: false

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
zuul:
  prefix: /api
  routes:
    ffkr-tournament:
      path: /tournament-service/**
      serviceId: ffkr-tournament
    ffkr-article:
      path: /article-service/**
      serviceId: ffkr-article
server:
  port: 8102
management:
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
zuul:
  prefix: /api           
  routes:
    ffkr-tournament:
      path: /games/**
      serviceId: ffkr-tournament
    ffkr-article:
      path: /articles/**
      serviceId: ffkr-article
server:
  port: 8102
