spring:
  data:
    jpa:
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
<<<<<<< HEAD
  datasource:
    url: jdbc:${db.vendor}://{db.host}:${db.port}/${db.database}
    username: ${db.user}
    password: ${db.password}
=======
>>>>>>> 9c9261ed4b8917789eebb26e5ab1bf1d5c998dcd
security:
  basic:
    enabled: false
eureka:
  instance:
    instanceId: ${spring.application.name}:${ffkr-tournament.instanceId}:${server.port}
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health,info,configprops
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    configprops:
      enabled: true
server:
  port: 8103

---

spring:
  profiles: local
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://ffkr-discovery:8100/eureka/
