spring:
  profiles: heroku
eureka:
  client:
    serviceUrl:
      defaultZone: https://ffkr-discovery-service.herokuapp.com/eureka/
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

---
spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ffkr
    username: os
    password: os
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8103
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
