spring:
  profiles: heroku
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: https://ffkr-discovery-service.herokuapp.com/eureka/
  instance:
    hostname: ffkr-tournament-service.herokuapp.com
    nonSecurePort: 80
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

---

spring:
  profiles: local
  datasource:
    url: jdbc:postgresql://localhost:5432/ffkr
    username: os
    password: os
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8103
security:
  basic:
    enabled: false
management:
  security:
    enabled: false

---

spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://tournament-db:5432/ffkr
    username: os
    password: os
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8100/eureka/
server:
  port: 8103
security:
  basic:
    enabled: false
management:
  security:
    enabled: false
